# Generated by Django 6.0.4 on 2026-05-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_connexion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
