# Generated by Django 6.0.4 on 2026-04-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('en_ligne', 'En ligne'), ('sur_place', 'Sur place')], max_length=20)),
                ('methode_paiement', models.CharField(blank=True, choices=[('carte', 'Carte Bancaire'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('especes', 'Espèces')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('effectue', 'Effectué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
