# Generated by Django 6.0.4 on 2026-04-29 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activites.creneau'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='formule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activites.formule'),
        ),
        migrations.AddField(
            model_name='enfant',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='reservations.reservation'),
        ),
    ]
