# Generated by Django 6.0.4 on 2026-05-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='enfant',
            name='prenom',
        ),
    ]
