# Generated by Django 6.0.4 on 2026-05-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_enfant_nom_remove_enfant_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
