# Generated by Django 6.0.4 on 2026-05-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_enfant_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(choices=[('en_ligne', 'En ligne'), ('sur_place', 'Sur place')], default='sur_place', max_length=20),
        ),
    ]
