# Generated by Django 6.0.4 on 2026-06-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_mode_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='mode_paiement',
        ),
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement_choisi',
            field=models.CharField(blank=True, choices=[('en_ligne', 'En ligne'), ('sur_place', 'Sur place')], default='sur_place', max_length=20),
        ),
    ]
