# Generated by Django 6.0.4 on 2026-04-29 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('piscine', 'Piscine'), ('aire_jeu', 'Aire de Jeu')], max_length=20)),
                ('capacite_max', models.IntegerField(default=50)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite_disponible', models.IntegerField()),
                ('statut', models.BooleanField(default=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='activites.activite')),
            ],
        ),
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('demi_journee', 'Demi-Journée'), ('journee_entiere', 'Journée Entière'), ('aire_jeu_1h', 'Aire de Jeu 1h'), ('aire_jeu_2h', 'Aire de Jeu 2h'), ('anniversaire', 'Anniversaire')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree', models.CharField(max_length=50)),
                ('gouter_inclus', models.BooleanField(default=False)),
                ('statut', models.BooleanField(default=True)),
                ('activites', models.ManyToManyField(blank=True, to='activites.activite')),
            ],
        ),
    ]
